trigger:
  branches:
    include:
      - refs/tags/v*

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: $(projectDockerRegistryServiceConnection)
  # Project root folder. Point to the folder file(s).
  projectRoot: $(System.DefaultWorkingDirectory)
  imageRepository: $(projectImageRepository)
  containerRegistry: $(projectContainerRegistry)
  dockerfilePath: "**/Dockerfile"
  tag: "$(Build.BuildId)"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        timeoutInMinutes: "10"
        cancelTimeoutInMinutes: "3"
        pool:
          name: $(projectPoolName)
          vmImage: $(vmImageName)
        steps:
          - script: |
              apt-get update
              apt-get install ca-certificates curl gnupg
              install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              chmod a+r /etc/apt/keyrings/docker.gpg

              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
                tee /etc/apt/sources.list.d/docker.list > /dev/null
              apt-get update
            workingDirectory: $(projectRoot)
            displayName: "Set up the Docker repository"

          - script: |
              apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y --allow-change-held-packages
            workingDirectory: $(projectRoot)
            displayName: "Install the Docker packages"

          - script: |
              service docker start
            workingDirectory: $(projectRoot)
            displayName: "Start the Docker service"

          - task: Docker@2
            displayName: "Build and push an image to container registry"
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
